#version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: agenda_hunter_db
    environment:
      POSTGRES_USER: hunter
      POSTGRES_PASSWORD: hunter
      POSTGRES_DB: agenda_hunter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
